[project]
name = "optimize_wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "munch>=4.0.0",
    "pygad>=3.5.0",
    "viktor>=14.24.0",
]
